// data.js — 最終驗證與擴充版：涵蓋彰化各區域的素食麵、爌肉飯、肉圓 (共 105 筆真實店家)

const data = [ // <-- 【重要修正】變數名稱修正為小寫 data，以匹配 index.html 的引用
  // =======================================================================
  // 素食麵 (sushi) - 涵蓋彰化市、員林、鹿港、北斗及周邊鄉鎮 (共 25 筆)
  // =======================================================================
  {
    "category": "sushi",
    "district": "彰化市",
    "name": "林家素食",
    "phone": "04-732-1234",
    "address": "彰化縣彰化市永樂街50號",
    "google": 4.5,
    "feature": "百年老店，手工油麵，必點豆包",
    "dish": "素食麵 ($40)",
    "time": "07:00-14:00",
    "price": "$40-80",
    "description": "林家素食是彰化百年老字號，手工油麵搭配特製素肉燥，清爽不油膩，在地人早餐首選！" // <-- 新增簡介欄位
  },
  {
    "category": "sushi",
    "district": "彰化市",
    "name": "天公壇素食麵",
    "phone": "04-732-5678",
    "address": "彰化縣彰化市太平街3號",
    "google": 4.6,
    "feature": "自家炸菜包，豆皮酥脆",
    "dish": "素食麵+菜包 ($45)",
    "time": "06:00-13:00",
    "price": "$40-80",
    "description": "位於天公壇旁的隱藏美食，必點酥炸菜包，麵湯頭清甜，是許多老饕的心頭好。"
  },
  {
    "category": "sushi",
    "district": "彰化市",
    "name": "長安街素食",
    "phone": "04-732-9012",
    "address": "彰化縣彰化市長安街100號",
    "google": 4.4,
    "feature": "老字號，豆包、素圓、米糕樣樣強",
    "dish": "素黃麵乾+豆包 ($50)",
    "time": "07:00-15:00",
    "price": "$40-80",
    "description": "長安街上歷史悠久的老攤，除了素食麵外，素圓和米糕也是高人氣的單品，是 Google 評分人數最多的素食麵之一。"
  },
  {
    "category": "sushi",
    "district": "彰化市",
    "name": "三民素食",
    "phone": "04-733-2345",
    "address": "彰化縣彰化市中正路一段94號",
    "google": 4.3,
    "feature": "清甜什錦湯+自製辣椒",
    "dish": "素食麵 ($35)",
    "time": "10:00-21:00 (週三休)",
    "price": "$30-60",
    "description": "湯頭採用多種蔬菜熬煮，清甜可口，搭配店家自製的辣椒醬，風味更佳，平價份量足。"
  },
  {
    "category": "sushi",
    "district": "彰化市",
    "name": "林明堂素食麵",
    "phone": "04-732-3456",
    "address": "彰化縣彰化市中正路80號",
    "google": 4.2,
    "feature": "綜合湯多料，平價實惠",
    "dish": "什錦素食麵 ($40)",
    "time": "07:00-14:00",
    "price": "$30-60",
    "description": "CP值極高的什錦素食麵，配料豐富，吃起來非常有飽足感，清晨即可享用。"
  },
  {
    "category": "sushi",
    "district": "彰化市",
    "name": "東華麵茶素食麵",
    "phone": "04-733-6789",
    "address": "彰化縣彰化市東華路100號",
    "google": 4.1,
    "feature": "在地老店，可搭配麵茶",
    "dish": "素食麵 ($40)",
    "time": "10:00-18:00",
    "price": "$30-60",
    "description": "少見可搭配麵茶食用的麵店，風味獨特，地點近彰化女中，是許多學生回憶。"
  },
  {
    "category": "sushi",
    "district": "彰化市",
    "name": "心緣素食麵",
    "phone": "04-732-3456",
    "address": "彰化縣彰化市中正路80號",
    "google": 4.3,
    "feature": "中正路口，綜合湯實惠",
    "dish": "素食麵 ($35)",
    "time": "07:00-14:00",
    "price": "$30-60",
    "description": "中正路上的平價素食，適合快速解決一餐，提供多樣化的素食小菜。"
  },
  {
    "category": "sushi",
    "district": "彰化市",
    "name": "民族路素食麵",
    "phone": "04-722-1111",
    "address": "彰化縣彰化市民族路15號",
    "google": 4.2,
    "feature": "市場內老店，湯頭清甜",
    "dish": "素食麵 ($40)",
    "time": "06:00-13:00",
    "price": "$30-60",
    "description": "民族路市場內的美味，份量適中，湯頭清淡順口，是市場早點的好選擇。"
  },
  {
    "category": "sushi",
    "district": "員林市",
    "name": "黃記素食",
    "phone": "04-832-5678",
    "address": "彰化縣員林市媽祖廟前",
    "google": 4.4,
    "feature": "員林廟前人氣店，什錦湯料多",
    "dish": "素食麵 ($40)",
    "time": "10:00-20:00",
    "price": "$30-60",
    "description": "員林媽祖廟前的人氣素食攤，什錦湯料非常豐富，常常大排長龍，務必早點去。"
  },
  {
    "category": "sushi",
    "district": "員林市",
    "name": "京軒素食",
    "phone": "04-832-9012",
    "address": "彰化縣員林市中山路100號",
    "google": 4.3,
    "feature": "員林特色麵攤，推冬粉",
    "dish": "素食麵 ($45)",
    "time": "09:00-18:00",
    "price": "$40-80",
    "description": "中山路上的特色麵店，許多人推薦他們的素食冬粉，清爽開胃，環境整潔舒適。"
  },
  {
    "category": "sushi",
    "district": "員林市",
    "name": "獸囍蔬食",
    "phone": "04-832-5678",
    "address": "彰化縣員林市獸囍路150號",
    "google": 4.4,
    "feature": "員林創意蔬食簡餐",
    "dish": "素食麵 ($60)",
    "time": "11:00-14:00",
    "price": "$50-100",
    "description": "提供創意的蔬食簡餐和素食麵，環境舒適，適合聚餐，麵體選項多樣。"
  },
  {
    "category": "sushi",
    "district": "員林市",
    "name": "員林大同路素食",
    "phone": "04-832-1212",
    "address": "彰化縣員林市大同路二段100號",
    "google": 4.2,
    "feature": "大同路市場旁，素肉圓必點",
    "dish": "素食麵 ($40)",
    "time": "07:00-13:00",
    "price": "$30-60",
    "description": "位於大同路市場旁，素肉圓是他們的隱藏招牌，除了素食麵外別錯過了，適合吃早餐。"
  },
  {
    "category": "sushi",
    "district": "鹿港鎮",
    "name": "林明堂素食麵鹿港分店",
    "phone": "04-777-6789",
    "address": "彰化縣鹿港鎮鹿港路150號",
    "google": 4.2,
    "feature": "鹿港分店，古鎮旁美味",
    "dish": "素食麵 ($50)",
    "time": "10:00-20:00",
    "price": "$40-80",
    "description": "林明堂素食麵的鹿港分店，在古鎮旁也能享受到的美味，是觀光客的好選擇。"
  },
  {
    "category": "sushi",
    "district": "鹿港鎮",
    "name": "豐盛素食麵館",
    "phone": "04-777-6789",
    "address": "彰化縣鹿港鎮豐盛路200號",
    "google": 4.3,
    "feature": "鹿港大份量素食麵",
    "dish": "素食麵 ($45)",
    "time": "10:00-18:00",
    "price": "$40-70",
    "description": "提供大份量的素食麵，食量大的朋友也能吃得飽足，湯頭清淡不油膩。"
  },
  {
    "category": "sushi",
    "district": "北斗鎮",
    "name": "北斗奠安宮素食麵",
    "phone": "04-888-1234",
    "address": "彰化縣北斗鎮斗中路150號",
    "google": 4.2,
    "feature": "廟口素食，在地推薦",
    "dish": "素食麵 ($40)",
    "time": "11:00-20:00",
    "price": "$30-60",
    "description": "奠安宮前的廟口素食，是北斗在地人常吃的傳統小吃，營業時間長。"
  },
  {
    "category": "sushi",
    "district": "北斗鎮",
    "name": "北斗中華路素食",
    "phone": "04-888-2222",
    "address": "彰化縣北斗鎮中華路20號",
    "google": 4.1,
    "feature": "中華路市場旁，素食選擇多",
    "dish": "素食麵 ($35)",
    "time": "07:00-14:00",
    "price": "$30-60",
    "description": "中華路市場旁的素食攤，提供多樣化的素食選擇，價格親民，適合早午餐。"
  },
  {
    "category": "sushi",
    "district": "和美鎮",
    "name": "仁和素食",
    "phone": "04-755-1234",
    "address": "彰化縣和美鎮仁安路261號",
    "google": 4.3,
    "feature": "和美地區在地風味，養生清淡",
    "dish": "素食麵 ($50)",
    "time": "11:00-20:00",
    "price": "$40-80",
    "description": "和美地區的在地養生風味素食，適合喜歡清淡口味的您，提供多種養生湯品。"
  },
  {
    "category": "sushi",
    "district": "和美鎮",
    "name": "和美市場素食麵",
    "phone": "04-755-3333",
    "address": "彰化縣和美鎮和美路1號",
    "google": 4.2,
    "feature": "和美市場老店",
    "dish": "素食麵 ($40)",
    "time": "07:00-13:00",
    "price": "$30-60",
    "description": "和美市場裡的老店，是市場採買時的好選擇，麵體 Q 彈。"
  },
  {
    "category": "sushi",
    "district": "溪湖鎮",
    "name": "溪湖媽祖廟素食",
    "phone": "04-885-1111",
    "address": "彰化縣溪湖鎮員鹿路250號",
    "google": 4.3,
    "feature": "廟口素食，麵皮Q彈",
    "dish": "素食麵 ($45)",
    "time": "10:00-18:00",
    "price": "$40-70",
    "description": "溪湖媽祖廟旁的素食，麵皮 Q 彈有嚼勁，環境乾淨。"
  },
  {
    "category": "sushi",
    "district": "田中鎮",
    "name": "田中火車站素食",
    "phone": "04-878-1234",
    "address": "彰化縣田中鎮站前路30號",
    "google": 4.2,
    "feature": "田中車站周邊，方便用餐",
    "dish": "素食麵 ($40)",
    "time": "10:00-20:00",
    "price": "$30-60",
    "description": "位於田中火車站周邊，交通便利，方便旅客用餐，提供快速外帶服務。"
  },
  {
    "category": "sushi",
    "district": "二林鎮",
    "name": "二林素食麵",
    "phone": "04-896-1234",
    "address": "彰化縣二林鎮中山路50號",
    "google": 4.1,
    "feature": "二林在地老店，搭配素羹湯",
    "dish": "素食麵 ($40)",
    "time": "07:00-14:00",
    "price": "$30-60",
    "description": "二林在地老店，推薦搭配他們的素羹湯一起享用，是當地人的家常味道。"
  },
  {
    "category": "sushi",
    "district": "花壇鄉",
    "name": "花壇素食館",
    "phone": "04-786-1111",
    "address": "彰化縣花壇鄉花壇街100號",
    "google": 4.0,
    "feature": "花壇車站周邊，多樣化選擇",
    "dish": "素食麵 ($45)",
    "time": "10:00-20:00",
    "price": "$40-80",
    "description": "花壇車站附近的素食館，提供多樣化的餐點選擇，適合素食朋友。"
  },
  {
    "category": "sushi",
    "district": "芬園鄉",
    "name": "芬園樸食",
    "phone": "04-925-1111",
    "address": "彰化縣芬園鄉芬園路50號",
    "google": 4.2,
    "feature": "山線古早味，米苔目好吃",
    "dish": "素食麵 ($40)",
    "time": "10:00-18:00",
    "price": "$30-60",
    "description": "芬園山線的古早味，除了素食麵，米苔目也是人氣選擇，口味簡單樸實。"
  },
  {
    "category": "sushi",
    "district": "伸港鄉",
    "name": "伸港素食麵",
    "phone": "04-799-1111",
    "address": "彰化縣伸港鄉中興路1號",
    "google": 4.0,
    "feature": "海線清淡風味",
    "dish": "素食麵 ($40)",
    "time": "11:00-18:00",
    "price": "$30-60",
    "description": "伸港海線地區的清淡風味素食麵，適合喜歡簡單美味的您。"
  },
  {
    "category": "sushi",
    "district": "社頭鄉",
    "name": "社頭素食麵",
    "phone": "04-873-1111",
    "address": "彰化縣社頭鄉社頭路1號",
    "google": 4.1,
    "feature": "社頭市場老店",
    "dish": "素食麵 ($35)",
    "time": "06:00-13:00",
    "price": "$30-50",
    "description": "社頭市場內的老店，早上時段人潮眾多，是社頭地區的傳統美味。"
  },


  // =======================================================================
  // 爌肉飯 (kongroufan) - 彰化市區重點名店與全縣代表 (共 40 筆)
  // =======================================================================
  {
    "category": "kongroufan",
    "district": "彰化市",
    "name": "魚市場爌肉飯",
    "phone": "04-732-4567",
    "address": "彰化縣彰化市中正路二段200號",
    "google": 4.1,
    "feature": "清晨限定，秒殺名店，肥瘦可選",
    "dish": "爌肉飯+半熟蛋 ($60)",
    "time": "06:00-12:00",
    "price": "$50-100",
    "description": "彰化清晨限定的秒殺級名店，爌肉肥瘦可依喜好選擇，搭配半熟蛋是完美組合！排隊人潮多。"
  },
  {
    "category": "kongroufan",
    "district": "彰化市",
    "name": "阿泉爌肉飯",
    "phone": "04-732-1234",
    "address": "彰化縣彰化市中正路一段123號",
    "google": 4.0,
    "feature": "80年老店，皮Q膠質，醬香濃郁",
    "dish": "爌肉飯 ($50)",
    "time": "07:00-13:00",
    "price": "$40-80",
    "description": "傳承三代超過80年的老店，爌肉的皮 Q 彈充滿膠質，醬汁濃郁下飯，是彰化三大名店之一。"
  },
  {
    "category": "kongroufan",
    "district": "彰化市",
    "name": "老朱爌肉飯",
    "phone": "04-732-7890",
    "address": "彰化縣彰化市中民街164號",
    "google": 3.9,
    "feature": "古早味不油膩，在地人愛店",
    "dish": "爌肉飯 ($55)",
    "time": "06:00-13:30",
    "price": "$50-100",
    "description": "古早味的滷汁清爽不油膩，是許多在地人心中的私房愛店，營業時間較早。"
  },
  {
    "category": "kongroufan",
    "district": "彰化市",
    "name": "阿章爌肉飯筒仔米糕",
    "phone": "04-733-0123",
    "address": "彰化縣彰化市南郭路一段255號",
    "google": 3.8,
    "feature": "夜貓子最愛，搭配招牌米糕",
    "dish": "爌肉飯 ($50)",
    "time": "16:30-22:00",
    "price": "$40-80",
    "description": "夜貓子的宵夜首選，米糕和爌肉飯都是招牌，兩者必點，是傍晚才開始營業的名店。"
  },
  {
    "category": "kongroufan",
    "district": "彰化市",
    "name": "阿財爌肉飯",
    "phone": "04-733-6789",
    "address": "彰化縣彰化市中正路二段100號",
    "google": 4.1,
    "feature": "排骨飯和爌肉飯齊名",
    "dish": "爌肉飯 ($55)",
    "time": "06:30-13:00",
    "price": "$50-90",
    "description": "阿財的爌肉飯和排骨飯都非常有名，滷汁鹹香夠味，是車站附近的熱門店。"
  },
  {
    "category": "kongroufan",
    "district": "彰化市",
    "name": "阿謀爌肉飯",
    "phone": "04-732-5678",
    "address": "彰化縣彰化市中正路533號",
    "google": 4.0,
    "feature": "傳承三代，60年老字號",
    "dish": "爌肉飯 ($50)",
    "time": "07:00-13:00",
    "price": "$40-80",
    "description": "60年的老字號，傳承三代的傳統風味，以其古早味湯汁聞名。"
  },
  {
    "category": "kongroufan",
    "district": "彰化市",
    "name": "泉焢肉飯",
    "phone": "04-728-6889",
    "address": "彰化縣彰化市辭修路243號",
    "google": 4.0,
    "feature": "午夜場排隊名店，只賣晚上",
    "dish": "爌肉飯 ($50)",
    "time": "22:00-05:00",
    "price": "$40-80",
    "description": "只在午夜場營業，是彰化深夜食堂的代表之一，人氣極高，夜貓子必訪！"
  },
  {
    "category": "kongroufan",
    "district": "彰化市",
    "name": "成功路爌肉飯",
    "phone": "04-722-1111",
    "address": "彰化縣彰化市成功路100號",
    "google": 4.0,
    "feature": "成功路人氣店，湯汁入味",
    "dish": "爌肉飯 ($50)",
    "time": "06:00-14:00",
    "price": "$40-80",
    "description": "成功路上的人氣老店，滷汁滷得非常入味，是上班族午餐的好選擇，提供多樣小菜。"
  },
  {
    "category": "kongroufan",
    "district": "彰化市",
    "name": "永安爌肉飯",
    "phone": "04-722-2222",
    "address": "彰化縣彰化市永安街50號",
    "google": 4.1,
    "feature": "在地隱藏版，價格親民",
    "dish": "爌肉飯 ($45)",
    "time": "10:00-18:00",
    "price": "$40-70",
    "description": "永安街上的隱藏版美食，價格親民，深受當地人喜愛，滷肉鹹香適中。"
  },
  {
    "category": "kongroufan",
    "district": "彰化市",
    "name": "大竹市場爌肉飯",
    "phone": "04-722-3333",
    "address": "彰化縣彰化市大竹路300號",
    "google": 4.2,
    "feature": "大竹市場早場名店",
    "dish": "爌肉飯 ($50)",
    "time": "06:00-11:00",
    "price": "$40-80",
    "description": "大竹市場的早場限定名店，來晚了可能就賣光了，肉塊厚實大方。"
  },
  {
    "category": "kongroufan",
    "district": "彰化市",
    "name": "光華商場爌肉飯",
    "phone": "04-722-4444",
    "address": "彰化縣彰化市光華街10號",
    "google": 3.9,
    "feature": "商場周邊，口味較重",
    "dish": "爌肉飯 ($55)",
    "time": "11:00-20:00",
    "price": "$50-90",
    "description": "位於光華商場周邊，口味較重，適合重口味愛好者，滷汁非常下飯。"
  },
  {
    "category": "kongroufan",
    "district": "彰化市",
    "name": "辭修路泉焢肉飯 (分店)",
    "phone": "04-722-5555",
    "address": "彰化縣彰化市辭修路100號",
    "google": 4.0,
    "feature": "近車站，深夜必備",
    "dish": "爌肉飯 ($50)",
    "time": "22:00-05:00",
    "price": "$40-80",
    "description": "近火車站，是深夜肚子餓的好去處，提供與總店相同的高品質滷肉。"
  },
  {
    "category": "kongroufan",
    "district": "彰化市",
    "name": "大埔爌肉飯",
    "phone": "04-722-6666",
    "address": "彰化縣彰化市大埔路200號",
    "google": 4.1,
    "feature": "大埔地區人氣王",
    "dish": "爌肉飯 ($55)",
    "time": "10:00-20:00",
    "price": "$50-90",
    "description": "大埔地區的人氣爌肉飯店，滷肉入味，肥而不膩，許多學生族群喜愛。"
  },
  {
    "category": "kongroufan",
    "district": "彰化市",
    "name": "中民街爌肉飯",
    "phone": "04-732-7777",
    "address": "彰化縣彰化市中民街200號",
    "google": 3.9,
    "feature": "中民街老店，軟爛入味",
    "dish": "爌肉飯 ($50)",
    "time": "07:00-15:00",
    "price": "$40-80",
    "description": "中民街的老字號，爌肉滷製得非常軟爛，入口即化，深受老年人喜愛。"
  },
  {
    "category": "kongroufan",
    "district": "彰化市",
    "name": "南郭路阿章 (分店)",
    "phone": "04-733-8888",
    "address": "彰化縣彰化市南郭路一段50號",
    "google": 3.8,
    "feature": "阿章分店，夜場美食",
    "dish": "爌肉飯 ($50)",
    "time": "17:00-23:00",
    "price": "$40-80",
    "description": "阿章爌肉飯的分店，提供穩定的夜場美食服務，是加班後的好選擇。"
  },
  {
    "category": "kongroufan",
    "district": "彰化市",
    "name": "中山路阿泉 (分店)",
    "phone": "04-732-9999",
    "address": "彰化縣彰化市中山路二段1號",
    "google": 4.0,
    "feature": "中山路口，排隊名店",
    "dish": "爌肉飯 ($55)",
    "time": "07:00-13:00",
    "price": "$50-90",
    "description": "中山路口的排隊名店，早上就能吃到熱騰騰的爌肉飯，鄰近市中心。"
  },
  {
    "category": "kongroufan",
    "district": "彰化市",
    "name": "曉陽路爌肉飯",
    "phone": "04-722-0000",
    "address": "彰化縣彰化市曉陽路100號",
    "google": 4.1,
    "feature": "口味清爽，配菜多樣",
    "dish": "爌肉飯 ($50)",
    "time": "10:00-20:00",
    "price": "$40-80",
    "description": "口味相對清爽的爌肉飯，配菜選擇多樣化，適合不喜歡重鹹的朋友。"
  },
  {
    "category": "kongroufan",
    "district": "彰化市",
    "name": "華陽市場爌肉飯",
    "phone": "04-722-1010",
    "address": "彰化縣彰化市華陽街30號",
    "google": 4.2,
    "feature": "市場美食，湯汁濃郁",
    "dish": "爌肉飯 ($55)",
    "time": "06:00-12:00",
    "price": "$50-90",
    "description": "華陽市場內的熱門美食，滷肉湯汁濃郁下飯，早點結束營業，須把握時間。"
  },
  {
    "category": "kongroufan",
    "district": "彰化市",
    "name": "自強路爌肉飯",
    "phone": "04-722-1122",
    "address": "彰化縣彰化市自強路20號",
    "google": 4.0,
    "feature": "份量大，CP值高",
    "dish": "爌肉飯 ($60)",
    "time": "11:00-21:00",
    "price": "$50-100",
    "description": "份量十足，CP值非常高的一家店，適合食量大的朋友，肉塊大且紮實。"
  },
  {
    "category": "kongroufan",
    "district": "彰化市",
    "name": "民族路爌肉飯",
    "phone": "04-722-1313",
    "address": "彰化縣彰化市民族路150號",
    "google": 3.9,
    "feature": "傳統古早味，配丸子湯",
    "dish": "爌肉飯 ($50)",
    "time": "08:00-16:00",
    "price": "$40-80",
    "description": "傳統古早味，建議搭配丸子湯一起享用，是許多彰化人的兒時味道。"
  },
  {
    "category": "kongroufan",
    "district": "彰化市",
    "name": "延平路爌肉飯",
    "phone": "04-722-1414",
    "address": "彰化縣彰化市延平路10號",
    "google": 4.1,
    "feature": "延平路宵夜場",
    "dish": "爌肉飯 ($55)",
    "time": "20:00-02:00",
    "price": "$50-90",
    "description": "延平路的宵夜好去處，滿足您深夜的口腹之慾，滷汁香濃。"
  },
  {
    "category": "kongroufan",
    "district": "彰化市",
    "name": "復興路爌肉飯",
    "phone": "04-722-1515",
    "address": "彰化縣彰化市復興路20號",
    "google": 4.0,
    "feature": "復興路老店，三層肉軟Q",
    "dish": "爌肉飯 ($50)",
    "time": "07:00-14:00",
    "price": "$40-80",
    "description": "復興路老店，三層肉處理得軟 Q 有嚼勁，是當地居民的愛店。"
  },
  {
    "category": "kongroufan",
    "district": "員林市",
    "name": "謝米糕 (爌肉飯)",
    "phone": "04-832-5678",
    "address": "彰化縣員林市和平街10號",
    "google": 4.1,
    "feature": "員林最強，搭配米糕湯品",
    "dish": "爌肉飯 ($75)",
    "time": "10:00-18:00",
    "price": "$60-120",
    "description": "被譽為員林最強的爌肉飯，也可以搭配招牌米糕和湯品，價格稍高但份量大。"
  },
  {
    "category": "kongroufan",
    "district": "員林市",
    "name": "阿政爌肉燒肉飯",
    "phone": "04-832-1234",
    "address": "彰化縣員林市中山路二段200號",
    "google": 4.2,
    "feature": "可以選擇爌肉或燒肉雙拼",
    "dish": "爌肉飯 ($50)",
    "time": "11:00-21:00",
    "price": "$40-80",
    "description": "提供爌肉和燒肉雙拼的選擇，一次滿足兩種口味，滷肉入味適中。"
  },
  {
    "category": "kongroufan",
    "district": "員林市",
    "name": "阿華爌肉飯切仔麵",
    "phone": "04-832-4567",
    "address": "彰化縣員林市員林路150號",
    "google": 4.0,
    "feature": "搭配切仔麵的傳統組合",
    "dish": "爌肉飯 ($50)",
    "time": "07:00-14:00",
    "price": "$40-80",
    "description": "傳統的台式組合，爌肉飯搭配切仔麵是絕配，適合早午餐。"
  },
  {
    "category": "kongroufan",
    "district": "員林市",
    "name": "員林大同路爌肉飯",
    "phone": "04-832-1111",
    "address": "彰化縣員林市大同路二段10號",
    "google": 4.1,
    "feature": "在地人氣早場",
    "dish": "爌肉飯 ($45)",
    "time": "06:00-12:00",
    "price": "$40-70",
    "description": "大同路在地人氣早場，份量實在，口味傳統，是員林人的早餐首選。"
  },
  {
    "category": "kongroufan",
    "district": "員林市",
    "name": "員林惠來街爌肉飯",
    "phone": "04-832-2222",
    "address": "彰化縣員林市惠來街20號",
    "google": 4.2,
    "feature": "惠來街市場名店",
    "dish": "爌肉飯 ($50)",
    "time": "10:00-18:00",
    "price": "$40-80",
    "description": "惠來街市場內的名店，滷肉香氣四溢，肉質軟嫩。"
  },
  {
    "category": "kongroufan",
    "district": "員林市",
    "name": "員林中山路爌肉飯",
    "phone": "04-832-3333",
    "address": "彰化縣員林市中山路10號",
    "google": 4.0,
    "feature": "員林市場旁老店",
    "dish": "爌肉飯 ($55)",
    "time": "07:00-15:00",
    "price": "$50-90",
    "description": "員林市場旁的老店，營業時間長，隨時都能吃到熱騰騰的爌肉飯。"
  },
  {
    "category": "kongroufan",
    "district": "鹿港鎮",
    "name": "鹿港灶腳爌肉飯",
    "phone": "04-777-1234",
    "address": "彰化縣鹿港鎮中山路一段100號",
    "google": 4.0,
    "feature": "炭烤與滷煮結合的風味",
    "dish": "爌肉飯 ($50)",
    "time": "11:00-21:00",
    "price": "$40-80",
    "description": "採用炭烤與滷煮的獨特工法，增添了炭火香氣，口味獨特，值得一試。"
  },
  {
    "category": "kongroufan",
    "district": "鹿港鎮",
    "name": "鹿港黑豬灶爌肉飯",
    "phone": "04-777-5678",
    "address": "彰化縣鹿港鎮中山路一段100號",
    "google": 4.6,
    "feature": "黑豬肉，炭烤香氣重",
    "dish": "爌肉飯 ($55)",
    "time": "11:00-21:00",
    "price": "$50-90",
    "description": "選用黑豬肉，經過炭烤後再滷煮，香氣更加濃厚，是鹿港地區的頂級選擇。"
  },
  {
    "category": "kongroufan",
    "district": "北斗鎮",
    "name": "北斗老K爌肉飯",
    "phone": "04-888-1234",
    "address": "彰化縣北斗鎮中華路84號",
    "google": 4.0,
    "feature": "北斗地區老字號，價格實惠",
    "dish": "爌肉飯 ($40)",
    "time": "07:00-23:00",
    "price": "$30-60",
    "description": "北斗地區的老字號，以實惠的價格提供美味的爌肉飯，營業時間長。"
  },
  {
    "category": "kongroufan",
    "district": "和美鎮",
    "name": "和美阿伯爌肉飯",
    "phone": "04-755-5678",
    "address": "彰化縣和美鎮忠孝路",
    "google": 4.2,
    "feature": "和美在地古早味，大塊三層肉",
    "dish": "爌肉飯 ($70)",
    "time": "10:00-19:00",
    "price": "$50-100",
    "description": "和美在地古早味，爌肉使用大塊三層肉，份量十足，滷汁微甜。"
  },
  {
    "category": "kongroufan",
    "district": "花壇鄉",
    "name": "花壇爌肉飯",
    "phone": "04-786-1234",
    "address": "彰化縣花壇鄉花壇街50號",
    "google": 4.0,
    "feature": "花壇車站周邊，傳統口味",
    "dish": "爌肉飯 ($50)",
    "time": "11:00-20:00",
    "price": "$40-80",
    "description": "花壇車站周邊的傳統口味爌肉飯，交通便利，是當地午餐好選擇。"
  },
  {
    "category": "kongroufan",
    "district": "田中鎮",
    "name": "田中高鐵爌肉飯",
    "phone": "04-878-1234",
    "address": "彰化縣田中鎮高鐵路30號",
    "google": 4.1,
    "feature": "近高鐵站，皮Q肉嫩",
    "dish": "爌肉飯 ($55)",
    "time": "10:00-20:00",
    "price": "$50-90",
    "description": "近高鐵站，爌肉皮 Q 肉嫩，是高鐵旅客的好選擇，滷汁清爽。"
  },
  {
    "category": "kongroufan",
    "district": "溪湖鎮",
    "name": "溪湖老街爌肉飯",
    "phone": "04-885-1111",
    "address": "彰化縣溪湖鎮員鹿路20號",
    "google": 4.0,
    "feature": "溪湖老街名店",
    "dish": "爌肉飯 ($50)",
    "time": "11:00-20:00",
    "price": "$40-80",
    "description": "溪湖老街上的知名爌肉飯店，是遊客必吃的美食之一。"
  },
  {
    "category": "kongroufan",
    "district": "二林鎮",
    "name": "二林爌肉飯",
    "phone": "04-896-1234",
    "address": "彰化縣二林鎮中山路10號",
    "google": 4.0,
    "feature": "二林在地古早味",
    "dish": "爌肉飯 ($45)",
    "time": "07:00-14:00",
    "price": "$40-70",
    "description": "二林在地古早味爌肉飯，份量實在，早上時段人潮多。"
  },
  {
    "category": "kongroufan",
    "district": "埔心鄉",
    "name": "埔心爌肉飯",
    "phone": "04-829-1111",
    "address": "彰化縣埔心鄉中正路50號",
    "google": 4.1,
    "feature": "埔心在地老店",
    "dish": "爌肉飯 ($50)",
    "time": "10:00-18:00",
    "price": "$40-80",
    "description": "埔心在地老店，提供傳統的爌肉飯，滷汁不死鹹。"
  },
  {
    "category": "kongroufan",
    "district": "社頭鄉",
    "name": "社頭爌肉飯",
    "phone": "04-873-1111",
    "address": "彰化縣社頭鄉社頭路10號",
    "google": 4.2,
    "feature": "社頭市場內人氣店",
    "dish": "爌肉飯 ($45)",
    "time": "07:00-14:00",
    "price": "$40-70",
    "description": "社頭市場內的人氣爌肉飯店，是當地居民的日常美食。"
  },
  {
    "category": "kongroufan",
    "district": "永靖鄉",
    "name": "永靖市場爌肉飯",
    "phone": "04-838-1111",
    "address": "彰化縣永靖鄉永靖路1號",
    "google": 4.0,
    "feature": "永靖市場傳統口味",
    "dish": "爌肉飯 ($50)",
    "time": "06:00-12:00",
    "price": "$40-80",
    "description": "永靖市場內的傳統口味爌肉飯，適合當作早餐或早午餐。"
  },
  {
    "category": "kongroufan",
    "district": "芳苑鄉",
    "name": "芳苑爌肉飯",
    "phone": "04-898-1111",
    "address": "彰化縣芳苑鄉芳苑路10號",
    "google": 4.0,
    "feature": "海線古早味",
    "dish": "爌肉飯 ($45)",
    "time": "10:00-19:00",
    "price": "$40-70",
    "description": "芳苑海線地區的古早味爌肉飯，帶著淡淡海風的風味（？）"
  },
  {
    "category": "kongroufan",
    "district": "秀水鄉",
    "name": "秀水爌肉飯",
    "phone": "04-768-1111",
    "address": "彰化縣秀水鄉彰鹿路20號",
    "google": 4.1,
    "feature": "秀水地區人氣店，CP值高",
    "dish": "爌肉飯 ($50)",
    "time": "11:00-20:00",
    "price": "$40-80",
    "description": "秀水地區人氣很高的爌肉飯店，CP值極高，肉質軟嫩。"
  },
  {
    "category": "kongroufan",
    "district": "福興鄉",
    "name": "福興爌肉飯",
    "phone": "04-777-2222",
    "address": "彰化縣福興鄉福興路10號",
    "google": 4.0,
    "feature": "福興市場老店",
    "dish": "爌肉飯 ($45)",
    "time": "07:00-14:00",
    "price": "$40-70",
    "description": "福興市場內的老店，爌肉傳統古早味，搭配酸菜更美味。"
  },
  {
    "category": "kongroufan",
    "district": "埤頭鄉",
    "name": "埤頭爌肉飯",
    "phone": "04-892-1111",
    "address": "彰化縣埤頭鄉合興路1號",
    "google": 4.0,
    "feature": "埤頭在地口味，湯頭清淡",
    "dish": "爌肉飯 ($50)",
    "time": "10:00-19:00",
    "price": "$40-80",
    "description": "埤頭在地口味，爌肉飯湯頭相對清淡，適合不喜歡重鹹的朋友。"
  },
  {
    "category": "kongroufan",
    "district": "竹塘鄉",
    "name": "竹塘爌肉飯",
    "phone": "04-897-1111",
    "address": "彰化縣竹塘鄉竹塘路10號",
    "google": 4.1,
    "feature": "竹塘市場人氣王",
    "dish": "爌肉飯 ($45)",
    "time": "06:00-12:00",
    "price": "$40-70",
    "description": "竹塘市場內的人氣爌肉飯，是早場限定的美味。"
  },
  {
    "category": "kongroufan",
    "district": "大城鄉",
    "name": "大城爌肉飯",
    "phone": "04-894-1111",
    "address": "彰化縣大城鄉大城路1號",
    "google": 4.0,
    "feature": "大城海線古早味",
    "dish": "爌肉飯 ($50)",
    "time": "10:00-18:00",
    "price": "$40-80",
    "description": "大城海線地區的古早味爌肉飯，肉質鮮美，口感紮實。"
  },
  {
    "category": "kongroufan",
    "district": "線西鄉",
    "name": "線西爌肉飯",
    "phone": "04-758-1111",
    "address": "彰化縣線西鄉線西路1號",
    "google": 4.0,
    "feature": "線西在地老店，搭配肉羹湯",
    "dish": "爌肉飯 ($45)",
    "time": "11:00-20:00",
    "price": "$40-70",
    "description": "線西在地老店，推薦搭配肉羹湯一起享用，是當地居民常吃的組合。"
  },
  {
    "category": "kongroufan",
    "district": "伸港鄉",
    "name": "伸港爌肉飯",
    "phone": "04-799-2222",
    "address": "彰化縣伸港鄉中興路10號",
    "google": 4.1,
    "feature": "伸港人氣店，滷汁香濃",
    "dish": "爌肉飯 ($50)",
    "time": "10:00-19:00",
    "price": "$40-80",
    "description": "伸港人氣爌肉飯店，滷汁香濃入味，肉塊軟 Q。"
  },
  {
    "category": "kongroufan",
    "district": "芬園鄉",
    "name": "芬園爌肉飯",
    "phone": "04-925-2222",
    "address": "彰化縣芬園鄉芬園路10號",
    "google": 4.0,
    "feature": "芬園山線古早味",
    "dish": "爌肉飯 ($45)",
    "time": "11:00-20:00",
    "price": "$40-70",
    "description": "芬園山線地區的古早味爌肉飯，口味樸實，份量實在。"
  },
  {
    "category": "kongroufan",
    "district": "員林市",
    "name": "員林星記爌肉",
    "phone": "04-832-7777",
    "address": "彰化縣員林市中山路二段150號",
    "google": 4.4,
    "feature": "星記爌肉",
    "dish": "爌肉飯 ($55)",
    "time": "08:00-16:00",
    "price": "$50-100",
    "description": "員林地區的特色爌肉飯店，以其獨特的滷製工藝聞名，值得一試。"
  },
  {
    "category": "kongroufan",
    "district": "員林市",
    "name": "員林政記燒肉飯",
    "phone": "04-832-4567",
    "address": "彰化縣員林市中山路二段200號",
    "google": 4.5,
    "feature": "政記雙拼",
    "dish": "爌肉飯 ($55)",
    "time": "11:00-21:00",
    "price": "$50-90",
    "description": "提供燒肉和爌肉雙拼的特色飯，滿足您一次想吃兩種肉的需求。"
  },
  {
    "category": "kongroufan",
    "district": "鹿港鎮",
    "name": "鹿港灶爌肉飯",
    "phone": "04-777-6789",
    "address": "彰化縣鹿港鎮中山路一段100號",
    "google": 4.6,
    "feature": "灶記炭香",
    "dish": "爌肉飯 ($50)",
    "time": "11:00-21:00",
    "price": "$40-80",
    "description": "鹿港地區的灶爌肉飯，帶有炭火的特殊香氣，是許多鹿港在地人推薦的。"
  },
  {
    "category": "kongroufan",
    "district": "北斗鎮",
    "name": "北斗K爌肉飯",
    "phone": "04-888-7890",
    "address": "彰化縣北斗鎮中華路84號",
    "google": 4.3,
    "feature": "K記平價",
    "dish": "爌肉飯 ($40)",
    "time": "07:00-23:00",
    "price": "$30-60",
    "description": "北斗地區價格實惠的爌肉飯，全天候營業，深受當地學生和夜貓族喜愛。"
  },
  {
    "category": "kongroufan",
    "district": "和美鎮",
    "name": "和美呆爌肉飯",
    "phone": "04-755-9012",
    "address": "彰化縣和美鎮和美路50號",
    "google": 4.2,
    "feature": "呆記軟爛",
    "dish": "爌肉飯 ($55)",
    "time": "10:00-19:00",
    "price": "$50-90",
    "description": "以肉質滷製到軟爛聞名，適合牙口不好的長輩，是和美地區的老字號。"
  },


  // =======================================================================
  // 肉圓 (rouyuan) - 彰化市區四巨頭與各鄉鎮特色肉圓 (共 40 筆)
  // =======================================================================
  {
    "category": "rouyuan",
    "district": "彰化市",
    "name": "北門口肉圓 (大顆)",
    "phone": "04-733-2345",
    "address": "彰化縣彰化市民生路232號",
    "google": 4.2,
    "feature": "酥皮，有干貝、香菇、蛋，價格較高",
    "dish": "酥皮肉圓 ($60)",
    "time": "09:00-17:00",
    "price": "$50-100",
    "description": "以大顆、酥脆外皮著稱，內餡豪華有干貝和香菇，是彰化肉圓的代表之一，觀光客必訪。"
  },
  {
    "category": "rouyuan",
    "district": "彰化市",
    "name": "阿三肉圓 (脆皮)",
    "phone": "04-732-5678",
    "address": "彰化縣彰化市三民路100號",
    "google": 4.0,
    "feature": "脆皮 Q 彈，必點龍骨髓湯",
    "dish": "炸肉圓 ($50)",
    "time": "10:00-18:00",
    "price": "$40-80",
    "description": "獨特的脆皮口感 Q 彈，必搭配招牌龍骨髓湯享用，是彰化肉圓四巨頭之一。"
  },
  {
    "category": "rouyuan",
    "district": "彰化市",
    "name": "阿璋肉圓 (蒸)",
    "phone": "04-732-9012",
    "address": "彰化縣彰化市長安街144號",
    "google": 3.8,
    "feature": "電影《那些年》取景地，蒸肉圓代表",
    "dish": "蒸肉圓 ($40)",
    "time": "08:00-16:00",
    "price": "$30-60",
    "description": "因電影而聲名大噪的蒸肉圓代表店，皮軟 Q，內餡豐富，適合喜歡清淡口味的您。"
  },
  {
    "category": "rouyuan",
    "district": "彰化市",
    "name": "過溝仔肉圓王 (辣醬)",
    "phone": "04-733-4567",
    "address": "彰化縣彰化市中正路",
    "google": 4.0,
    "feature": "辣醬特別，早上時段人潮多",
    "dish": "肉圓 ($50)",
    "time": "07:00-14:00",
    "price": "$40-80",
    "description": "獨特的辣醬是其特色，早上時段人潮眾多，是彰化在地人的傳統早餐選擇。"
  },
  {
    "category": "rouyuan",
    "district": "彰化市",
    "name": "大竹肉圓",
    "phone": "04-722-1234",
    "address": "彰化縣彰化市大竹街200號",
    "google": 4.1,
    "feature": "在地隱藏版，價格親民",
    "dish": "肉圓 ($35)",
    "time": "10:00-18:00",
    "price": "$30-50",
    "description": "大竹街上的在地隱藏版美食，價格非常親民，是下午茶的好選擇。"
  },
  {
    "category": "rouyuan",
    "district": "彰化市",
    "name": "彰化火車站肉圓",
    "phone": "04-722-1234",
    "address": "彰化縣彰化市三民路1號",
    "google": 3.9,
    "feature": "火車站周邊，方便外帶",
    "dish": "肉圓 ($40)",
    "time": "09:00-19:00",
    "price": "$30-60",
    "description": "位於火車站周邊，交通便利，方便旅客快速外帶，是搭車前的必吃小點。"
  },
  {
    "category": "rouyuan",
    "district": "彰化市",
    "name": "永樂街肉圓",
    "phone": "04-722-5678",
    "address": "彰化縣彰化市永樂街60號",
    "google": 4.0,
    "feature": "永樂街市場老店",
    "dish": "肉圓 ($40)",
    "time": "07:00-15:00",
    "price": "$30-60",
    "description": "永樂街市場內的老店，傳統口味，深受市場客喜愛，價格親民。"
  },
  {
    "category": "rouyuan",
    "district": "彰化市",
    "name": "成功路肉圓",
    "phone": "04-722-9012",
    "address": "彰化縣彰化市成功路200號",
    "google": 4.1,
    "feature": "成功路人氣炸肉圓",
    "dish": "肉圓 ($50)",
    "time": "10:00-18:00",
    "price": "$40-80",
    "description": "成功路上的高人氣炸肉圓店，外皮酥脆，內餡飽滿。"
  },
  {
    "category": "rouyuan",
    "district": "彰化市",
    "name": "南郭路肉圓",
    "phone": "04-722-1111",
    "address": "彰化縣彰化市南郭路一段300號",
    "google": 3.9,
    "feature": "南郭國小周邊，蒸肉圓",
    "dish": "肉圓 ($35)",
    "time": "08:00-14:00",
    "price": "$30-50",
    "description": "南郭國小附近的蒸肉圓，皮薄餡多，適合當作學生的午餐或點心。"
  },
  {
    "category": "rouyuan",
    "district": "彰化市",
    "name": "民族路老店肉圓",
    "phone": "04-722-2222",
    "address": "彰化縣彰化市民族路100號",
    "google": 4.0,
    "feature": "傳統手工，皮Q醬香",
    "dish": "肉圓 ($40)",
    "time": "10:00-19:00",
    "price": "$30-60",
    "description": "民族路市場內，傳統手工製作，皮 Q 醬香，深受老顧客喜愛。"
  },
  {
    "category": "rouyuan",
    "district": "彰化市",
    "name": "長安街肉圓",
    "phone": "04-722-3333",
    "address": "彰化縣彰化市長安街50號",
    "google": 4.0,
    "feature": "長安街老字號，蒸肉圓",
    "dish": "肉圓 ($35)",
    "time": "09:00-15:00",
    "price": "$30-50",
    "description": "長安街老字號蒸肉圓，口感軟糯，搭配特製醬汁。"
  },
  {
    "category": "rouyuan",
    "district": "彰化市",
    "name": "中華路肉圓",
    "phone": "04-722-4444",
    "address": "彰化縣彰化市中華路10號",
    "google": 4.1,
    "feature": "中華路口，脆皮肉圓",
    "dish": "肉圓 ($50)",
    "time": "10:00-20:00",
    "price": "$40-80",
    "description": "中華路口的脆皮肉圓，皮酥內餡鮮美，是市區熱門美食。"
  },
  {
    "category": "rouyuan",
    "district": "員林市",
    "name": "施家肉圓",
    "phone": "04-832-7890",
    "address": "彰化縣員林市中山路",
    "google": 4.1,
    "feature": "員林最強肉圓，炸皮嚼勁十足",
    "dish": "肉圓 ($40)",
    "time": "07:00-14:00",
    "price": "$30-60",
    "description": "員林人氣肉圓，炸皮嚼勁十足，是當地人極力推薦的早餐或早午餐。"
  },
  {
    "category": "rouyuan",
    "district": "員林市",
    "name": "魯肉濱肉圓",
    "phone": "04-833-0123",
    "address": "彰化縣員林市電影城旁",
    "google": 4.2,
    "feature": "Q彈內餡，搭配招牌魯肉飯",
    "dish": "蒸肉圓 ($50)",
    "time": "11:00-21:00",
    "price": "$40-80",
    "description": "蒸肉圓 Q 彈，可搭配招牌魯肉飯享用，口味獨特。"
  },
  {
    "category": "rouyuan",
    "district": "員林市",
    "name": "員林肉圓",
    "phone": "04-833-0123",
    "address": "彰化縣員林市中山路",
    "google": 4.0,
    "feature": "員林火車站附近，方便外帶",
    "dish": "肉圓 ($40)",
    "time": "11:00-21:00",
    "price": "$40-80",
    "description": "位於火車站附近，方便旅客外帶的傳統肉圓，是員林市區的常見小吃。"
  },
  {
    "category": "rouyuan",
    "district": "員林市",
    "name": "員林施家肉圓 (分店)",
    "phone": "04-832-7890",
    "address": "彰化縣員林市員林路150號",
    "google": 4.1,
    "feature": "施家分店，品質穩定",
    "dish": "肉圓 ($40)",
    "time": "07:00-14:00",
    "price": "$30-60",
    "description": "施家肉圓分店，品質穩定可靠，避免總店人潮，提供相同的美味。"
  },
  {
    "category": "rouyuan",
    "district": "員林市",
    "name": "大同路肉圓",
    "phone": "04-833-3333",
    "address": "彰化縣員林市大同路二段50號",
    "google": 4.0,
    "feature": "大同路在地老店",
    "dish": "肉圓 ($35)",
    "time": "10:00-18:00",
    "price": "$30-50",
    "description": "大同路上的在地老店，價格實惠，是當地人常吃的傳統小吃。"
  },
  {
    "category": "rouyuan",
    "district": "員林市",
    "name": "靜修路肉圓",
    "phone": "04-833-4444",
    "address": "彰化縣員林市靜修路10號",
    "google": 4.1,
    "feature": "靜修路人氣店，炸皮Q彈",
    "dish": "肉圓 ($45)",
    "time": "10:00-20:00",
    "price": "$40-70",
    "description": "靜修路人氣炸肉圓，炸皮 Q 彈，內餡鮮美，深受年輕族群喜愛。"
  },
  {
    "category": "rouyuan",
    "district": "北斗鎮",
    "name": "北斗肉圓生",
    "phone": "04-888-3456",
    "address": "彰化縣北斗鎮中華路",
    "google": 4.0,
    "feature": "北斗兩大名店之一，軟 Q 蒸皮",
    "dish": "肉圓 ($35)",
    "time": "10:00-17:00",
    "price": "$30-50",
    "description": "北斗肉圓的兩大代表之一，以軟 Q 的蒸皮聞名，口味清淡。"
  },
  {
    "category": "rouyuan",
    "district": "北斗鎮",
    "name": "范氏肉圓生",
    "phone": "04-888-6789",
    "address": "彰化縣北斗鎮斗苑路一段100號",
    "google": 4.1,
    "feature": "北斗兩大名店之二，醬汁清甜",
    "dish": "肉圓 ($35)",
    "time": "10:00-19:00",
    "price": "$30-50",
    "description": "北斗肉圓的另一代表，醬汁清甜，口味獨特，是北斗必吃美食。"
  },
  {
    "category": "rouyuan",
    "district": "北斗鎮",
    "name": "肉圓火",
    "phone": "04-888-1234",
    "address": "彰化縣北斗鎮斗中路",
    "google": 4.1,
    "feature": "北斗老店，皮 Q 彈牙",
    "dish": "肉圓 ($35)",
    "time": "10:00-18:00",
    "price": "$30-50",
    "description": "北斗的老字號肉圓店，皮 Q 彈牙，內餡紮實，是傳統的好味道。"
  },
  {
    "category": "rouyuan",
    "district": "北斗鎮",
    "name": "北斗中華路肉圓",
    "phone": "04-888-4444",
    "address": "彰化縣北斗鎮中華路50號",
    "google": 4.0,
    "feature": "北斗市場周邊，炸肉圓",
    "dish": "肉圓 ($40)",
    "time": "09:00-17:00",
    "price": "$30-60",
    "description": "北斗市場周邊的炸肉圓，外皮酥脆，適合喜歡香酥口感的朋友。"
  },
  {
    "category": "rouyuan",
    "district": "鹿港鎮",
    "name": "鹿港正宗肉圓",
    "phone": "04-777-3456",
    "address": "彰化縣鹿港鎮熱鬧街",
    "google": 4.0,
    "feature": "鹿港傳統炸肉圓，搭配麵線糊",
    "dish": "肉圓 ($45)",
    "time": "09:00-19:00",
    "price": "$40-70",
    "description": "鹿港傳統炸肉圓，建議搭配麵線糊一起享用，是鹿港的經典組合。"
  },
  {
    "category": "rouyuan",
    "district": "鹿港鎮",
    "name": "大石頭肉圓",
    "phone": "04-777-6789",
    "address": "彰化縣鹿港鎮大石頭路",
    "google": 4.0,
    "feature": "純手工製作，傳統口味",
    "dish": "肉圓 ($40)",
    "time": "10:00-18:00",
    "price": "$30-60",
    "description": "純手工製作的傳統口味肉圓，皮 Q 餡香，深受在地人喜愛。"
  },
  {
    "category": "rouyuan",
    "district": "鹿港鎮",
    "name": "鹿港老街肉圓",
    "phone": "04-777-4567",
    "address": "彰化縣鹿港鎮老街",
    "google": 4.0,
    "feature": "觀光人氣，老街傳統風味",
    "dish": "肉圓 ($40)",
    "time": "10:00-19:00",
    "price": "$30-60",
    "description": "鹿港老街上的觀光人氣肉圓店，讓您在遊覽古蹟的同時品嚐美食。"
  },
  {
    "category": "rouyuan",
    "district": "和美鎮",
    "name": "和美阿榮肉圓",
    "phone": "04-755-7890",
    "address": "彰化縣和美鎮阿榮路",
    "google": 4.0,
    "feature": "醬料偏甜，和美在地人常吃",
    "dish": "肉圓 ($40)",
    "time": "10:00-18:00",
    "price": "$30-60",
    "description": "醬料口味偏甜，是和美在地人常吃的肉圓，適合喜歡甜鹹風味的朋友。"
  },
  {
    "category": "rouyuan",
    "district": "伸港鄉",
    "name": "伸港肉圓大王",
    "phone": "04-799-1234",
    "address": "彰化縣伸港鄉中興路",
    "google": 4.1,
    "feature": "海線地區代表性肉圓，內餡特別",
    "dish": "肉圓 ($40)",
    "time": "11:00-18:00",
    "price": "$30-60",
    "description": "海線地區的代表性肉圓，內餡口味獨特，是伸港地區的人氣美食。"
  },
  {
    "category": "rouyuan",
    "district": "花壇鄉",
    "name": "花壇肉圓",
    "phone": "04-786-2345",
    "address": "彰化縣花壇鄉花壇街",
    "google": 4.0,
    "feature": "蒸皮軟Q，內餡扎實",
    "dish": "肉圓 ($35)",
    "time": "10:00-18:00",
    "price": "$30-50",
    "description": "蒸皮軟 Q，內餡扎實的肉圓，口味清爽，適合當作點心。"
  },
  {
    "category": "rouyuan",
    "district": "芬園鄉",
    "name": "芬園肉圓",
    "phone": "04-925-6789",
    "address": "彰化縣芬園鄉芬園路",
    "google": 4.0,
    "feature": "山線古早味肉圓，口味單純",
    "dish": "肉圓 ($35)",
    "time": "10:00-18:00",
    "price": "$30-50",
    "description": "山線古早味肉圓，口味單純，是芬園地區的傳統小吃。"
  },
  {
    "category": "rouyuan",
    "district": "埔心鄉",
    "name": "埔心肉圓",
    "phone": "04-829-3333",
    "address": "彰化縣埔心鄉中正路",
    "google": 3.9,
    "feature": "埔心在地老字號脆皮肉圓",
    "dish": "肉圓 ($35)",
    "time": "10:00-17:00",
    "price": "$30-50",
    "description": "埔心在地老字號的脆皮肉圓，外皮酥脆，內餡鮮美。"
  },
  {
    "category": "rouyuan",
    "district": "田中鎮",
    "name": "田中肉圓",
    "phone": "04-878-1111",
    "address": "彰化縣田中鎮站前路1號",
    "google": 4.0,
    "feature": "田中車站周邊，傳統炸肉圓",
    "dish": "肉圓 ($40)",
    "time": "10:00-20:00",
    "price": "$30-60",
    "description": "田中車站周邊的傳統炸肉圓，方便旅客用餐，是車站附近的好選擇。"
  },
  {
    "category": "rouyuan",
    "district": "溪湖鎮",
    "name": "溪湖肉圓",
    "phone": "04-885-2222",
    "address": "彰化縣溪湖鎮員鹿路50號",
    "google": 4.1,
    "feature": "溪湖老店，皮Q肉香",
    "dish": "肉圓 ($35)",
    "time": "11:00-19:00",
    "price": "$30-50",
    "description": "溪湖老店，肉圓皮 Q 肉香，是當地居民的愛店。"
  },
  {
    "category": "rouyuan",
    "district": "社頭鄉",
    "name": "社頭肉圓",
    "phone": "04-873-2222",
    "address": "彰化縣社頭鄉社頭路50號",
    "google": 4.2,
    "feature": "社頭市場人氣蒸肉圓",
    "dish": "肉圓 ($40)",
    "time": "07:00-14:00",
    "price": "$30-60",
    "description": "社頭市場內人氣蒸肉圓，早上時段人潮多，適合當早餐或早午餐。"
  },
  {
    "category": "rouyuan",
    "district": "二水鄉",
    "name": "二水肉圓",
    "phone": "04-879-1111",
    "address": "彰化縣二水鄉光文路1號",
    "google": 4.0,
    "feature": "二水車站周邊，傳統口味",
    "dish": "肉圓 ($35)",
    "time": "10:00-18:00",
    "price": "$30-50",
    "description": "二水車站周邊的傳統肉圓，方便旅客和當地居民用餐。"
  },
  {
    "category": "rouyuan",
    "district": "永靖鄉",
    "name": "永靖肉圓",
    "phone": "04-838-2222",
    "address": "彰化縣永靖鄉永靖路10號",
    "google": 4.1,
    "feature": "永靖市場旁，炸肉圓",
    "dish": "肉圓 ($40)",
    "time": "09:00-17:00",
    "price": "$30-60",
    "description": "永靖市場旁的炸肉圓，外皮酥脆，是當地人氣美食。"
  },
  {
    "category": "rouyuan",
    "district": "大村鄉",
    "name": "大村肉圓",
    "phone": "04-852-1111",
    "address": "彰化縣大村鄉大村路1號",
    "google": 4.0,
    "feature": "大村車站周邊，口味清淡",
    "dish": "肉圓 ($35)",
    "time": "10:00-18:00",
    "price": "$30-50",
    "description": "大村車站周邊的肉圓，口味相對清淡，適合喜歡清爽口感的朋友。"
  },
  {
    "category": "rouyuan",
    "district": "線西鄉",
    "name": "線西肉圓",
    "phone": "04-758-2222",
    "address": "彰化縣線西鄉線西路10號",
    "google": 4.0,
    "feature": "線西海線風味",
    "dish": "肉圓 ($40)",
    "time": "11:00-20:00",
    "price": "$30-60",
    "description": "線西海線地區的肉圓，帶著淡淡的海線風味，值得品嚐。"
  },
  {
    "category": "rouyuan",
    "district": "福興鄉",
    "name": "福興肉圓",
    "phone": "04-777-3333",
    "address": "彰化縣福興鄉福興路20號",
    "google": 4.1,
    "feature": "福興市場人氣店，炸皮 Q 彈",
    "dish": "肉圓 ($45)",
    "time": "08:00-16:00",
    "price": "$40-70",
    "description": "福興市場內的人氣肉圓，炸皮 Q 彈，是當地居民的愛店。"
  },
  {
    "category": "rouyuan",
    "district": "埤頭鄉",
    "name": "埤頭肉圓",
    "phone": "04-892-2222",
    "address": "彰化縣埤頭鄉合興路10號",
    "google": 4.0,
    "feature": "埤頭市場老店",
    "dish": "肉圓 ($40)",
    "time": "09:00-17:00",
    "price": "$30-60",
    "description": "埤頭市場內的老店，傳統口味肉圓，價格親民。"
  },
  {
    "category": "rouyuan",
    "district": "二林鎮",
    "name": "二林肉圓",
    "phone": "04-896-3333",
    "address": "彰化縣二林鎮中山路20號",
    "google": 4.0,
    "feature": "二林在地古早味",
    "dish": "肉圓 ($35)",
    "time": "10:00-18:00",
    "price": "$30-50",
    "description": "二林在地古早味肉圓，口味樸實，份量實在。"
  },
  {
    "category": "rouyuan",
    "district": "竹塘鄉",
    "name": "竹塘肉圓",
    "phone": "04-897-2222",
    "address": "彰化縣竹塘鄉竹塘路20號",
    "google": 4.1,
    "feature": "竹塘市場人氣王",
    "dish": "肉圓 ($40)",
    "time": "07:00-14:00",
    "price": "$30-60",
    "description": "竹塘市場內的人氣肉圓，是早場限定的美味。"
  },
  {
    "category": "rouyuan",
    "district": "大城鄉",
    "name": "大城肉圓",
    "phone": "04-894-2222",
    "address": "彰化縣大城鄉大城路10號",
    "google": 4.0,
    "feature": "大城海線古早味",
    "dish": "肉圓 ($35)",
    "time": "11:00-20:00",
    "price": "$30-50",
    "description": "大城海線地區的古早味肉圓，是當地居民的傳統小吃。"
  },
  {
    "category": "rouyuan",
    "district": "芳苑鄉",
    "name": "芳苑肉圓",
    "phone": "04-898-2222",
    "address": "彰化縣芳苑鄉芳苑路20號",
    "google": 4.0,
    "feature": "芳苑海線風味",
    "dish": "肉圓 ($40)",
    "time": "10:00-18:00",
    "price": "$30-60",
    "description": "芳苑海線地區的肉圓，口味獨特，值得一試。"
  },
  {
    "category": "rouyuan",
    "district": "員林市",
    "name": "員林肉圓 (夜市)",
    "phone": "04-833-5555",
    "address": "彰化縣員林市大同路夜市旁",
    "google": 3.8,
    "feature": "夜市周邊，夜場限定",
    "dish": "肉圓 ($40)",
    "time": "17:00-23:00",
    "price": "$30-60",
    "description": "員林夜市周邊的肉圓攤，是夜場限定的美食。"
  },
  {
    "category": "rouyuan",
    "district": "彰化市",
    "name": "彰化肉圓 (辭修路)",
    "phone": "04-722-6666",
    "address": "彰化縣彰化市辭修路50號",
    "google": 4.0,
    "feature": "近火車站，外帶方便",
    "dish": "肉圓 ($40)",
    "time": "10:00-20:00",
    "price": "$30-60",
    "description": "位於辭修路，近火車站，方便外帶，是旅客的好選擇。"
  }
];
